"""Add onboarding_completed

Revision ID: 87a0cbcabe16
Revises: c1b448e3c678
Create Date: 2026-08-08 18:11:26.179099

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87a0cbcabe16"
down_revision: str | Sequence[str] | None = "c1b448e3c678"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("onboarding_completed", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_completed")
    # ### end Alembic commands ###
