"""Initial

Revision ID: b29765c615d4
Revises:
Create Date: 2026-08-06 22:35:39.604963

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b29765c615d4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
