"""Add Google Auth

Revision ID: c1b448e3c678
Revises: 5e7cbf1f1ea2
Create Date: 2026-08-08 13:50:35.228565

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b448e3c678"
down_revision: str | Sequence[str] | None = "5e7cbf1f1ea2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("profile_image", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("auth_provider", sa.String(), nullable=False, server_default="email"),
    )
    op.add_column("users", sa.Column("google_subject", sa.String(), nullable=True))
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_users_google_subject"), "users", ["google_subject"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_subject"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "google_subject")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "profile_image")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
